-- Migration 119: Add nullable idle_since to sessions — the session's real
-- LAST-ACTIVITY boundary, so the quick-session board's "quiet for N" label
-- stops being reset by unrelated writes.
--
-- Until now the board derived idleSince from sessions.updated_at, which is a
-- proxy: updated_at is bumped by ANY write to the row (a rename, a folder move,
-- the boot sweep, a status refinement), so the quiet clock restarted on events
-- that were not activity at all. idle_since is written ONLY at the busy→resting
-- status transition, inside Database.updateSession's single UPDATE — the one
-- chokepoint every session-status write in the app already funnels through
-- (sessionManager.updateSession, sessionManager's system/result writer,
-- events.ts's all-panels-stopped check, the facade rester) — so it inherits
-- every substrate (claude-sdk / claude-interactive / codex-sdk / codex-pty /
-- omp-sdk / omp-pty) without a per-manager wire point.
--
-- Semantics:
--   NULL            = busy (running/pending). Readers COALESCE to updated_at,
--                     which keeps a not-yet-stamped row reading exactly as it
--                     did before this column existed.
--   datetime('now') = the moment the session came to rest. Same space-separated
--                     UTC format as CURRENT_TIMESTAMP/updated_at, so readers
--                     normalize it with the same strftime() the ' ' vs 'T'
--                     ordering trap already forces them to use.
--
-- Pre-existing resting rows are backfilled by 120, NOT here. The COALESCE
-- fallback alone is not enough for them: it is only equivalent to a real stamp
-- at the INSTANT of migration. A legacy row keeps idle_since NULL until its
-- next busy→resting transition, and in the meantime any write that bumps
-- updated_at without supplying a status — a rename, a folder move — drags the
-- COALESCE forward and resets the quiet clock, which is the original bug
-- verbatim. A parked idle chat session (exactly the population the board
-- renders) may never transition again, so that window is permanent, not
-- transient. See 120's header for why it is a separate file.
--
-- Plain nullable ADD COLUMN, no FK/CHECK, same rationale as 113/114 and
-- design_idea_id (082): sessions is a legacy table and integrity is
-- chokepoint-enforced.
--
-- Single-statement file for the replay hazard documented in 113's and 088's
-- headers: runFileBasedMigrations() execs a whole file in one transaction, and
-- a duplicate-column ALTER on re-run rolls that transaction back before any
-- later statement in the same file can apply.
--
-- NOTE: runFileBasedMigrations() in database.ts wraps every file in a
-- this.transaction(...) call, so no explicit BEGIN/COMMIT here.

ALTER TABLE sessions ADD COLUMN idle_since TEXT;
